#Makefile pour Projet 
all: main

main: main.o fonctionsMaths.o Trame.o IpFrame.o
	g++ -m32 -o main main.o fonctionsMaths.o IpFrame.o Trame.o

main.o: main.cpp fonctionsMaths.h IpFrame.h Trame.h
	g++ -m32 -Wall -c main.cpp

fonctionsMaths.o: fonctionsMaths.cpp fonctionsMaths.h
	g++ -m32 -Wall -c fonctionsMaths.cpp

Trame.o: Trame.cpp Trame.h
	g++ -m32 -Wall -c Trame.cpp

IpFrame.o: IpFrame.cpp IpFrame.h Data.h
	g++ -m32 -Wall -c IpFrame.cpp 

Data.o: Data.cpp Data.h fonctionsMaths.h
	g++ -m32 -Wall -c Data.cpp 

clean: 
	rm -f main *.o
	
