#Makefile pour Projet 

main: main.cpp 
	g++ -o main main.cpp

Data : Data.h
	g++ -o Data Data.o 

Data.o: Data.cpp
	g++ -o Data Data.cpp Data.h

Trame: Trame.h 
	g++ -o Trame Trame.o

Trame.o: Trame.cpp
	g++ -o Trame Trame.cpp Trame.h 

functionsMaths: functionsMaths.h
	g++ -o functionsMaths functionsMaths.o

functionsMaths.o: functionsMaths.cpp functionsMaths.h
	g++ -o functionsMaths functionsMaths.cpp 

IpFrame: IpFrame.h
	g++ -o IpFrame IpFrame.o

IpFrame.o: IpFrame.cpp IpFrame.h
	g++ -o IpFrame IpFrame.cpp 

clean: 
	rm -f main Trame.o functionsMaths.o IpFrame.o 



	
